name: Continuous integration

on: [pull_request, push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
# octokit types problem ?
#      - run: npm run lint
      - run: npm run build
      - run: npm run test
